name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt update
        sudo apt upgrade
        make
    - name: Test
      run: |
       ./compressor -c compressor compressed.bin
       ./compressor -d compressed.bin compress.bin
       ./compress.bin
