name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Build
      run: |
        make
    - name: Test
      run: |
       ./compressor -c compressor compressed.bin
       ./compressor -d compressed.bin compress.bin
       ./compress.bin
